name: Django Github Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-verison: [3.11]
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python Version ${{ matrix.python-version }}
      uses: actions/setup-python@v4.7.1
      with:
        python-version: ${{matrix.python-verison}}
    - name: Install Dependency for django
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  deploy:
    runs-on: ubuntu-latest
    name: deploy djanog app on heruku
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HERUKU_SECRET_KEY}}
          heroku_app_name: ${{secrets.HERUKU_SECRET_NAME}}
          heroku_email: "asadfe24@gmail.com"
          branch: "main"