name: Django Github Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-verison: [3.10,1.11]
    
    steps:
    - uses: action/checkout@v3
    - name: Setup Python Version ${{ matrix.python-version }}
      uses: actions/setup-python@v4.7.1
      with:
      python-version: ${{matrix.python-verison}}
    - name: Install Dependency for django
      run:
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      